import { useEffect, useRef, useState } from "react";
import { LineChart, Line, XAxis, YAxis, Tooltip, ResponsiveContainer, ReferenceLine } from "recharts";
import { Replay, loadScene, type Recording, type SceneData } from "./replay";
import { loadRecording, SyncedVideo } from "./locomotion";
import { Button } from "@/components/ui/button";
import { Slider } from "@/components/ui/slider";
import { Play, Pause, RotateCcw } from "lucide-react";

type Outcome = {trial:number; seed:number; motion_passed:boolean; native_contact_gate_passed:boolean; net_turns:number; hold_ok:boolean; drop:boolean};
type Evaluation = {trials:Outcome[]; motion_successes:number; native_contact_successes:number; method:string};

type Comparison = {rows:{id:string;motion_successes:number;native_contact_successes:number;trials:number;selected_trial_third_turn_s:number|null}[]};
const labels:Record<string,string>={ideal:"Simplified · fixed torque limit",motor:"Motor-aware · cold", "motor-hot":"Motor-aware · 100°C start",baseline:"Native Sharpa",weak:"25% torque ceiling",heavy:"+50% hand mass / inertia"};
const fingers=["Thumb","Index","Middle","Ring","Pinky"];
export default function PenSpinning() {
  const [variant,setVariant]=useState("motor");
  const [trialView,setTrialView]=useState("paired");
  const [ideal,setIdeal]=useState<Recording|null>(null);
  const [joint,setJoint]=useState(0);
  useEffect(()=>{let active=true;setIdeal(null);loadRecording(`./data/pen/ideal${trialView==="first"?"/first":""}`).then(r=>{if(active)setIdeal(r)}).catch(()=>{});return()=>{active=false}},[trialView]);
  const [comparison,setComparison]=useState<Comparison|null>(null);
  useEffect(()=>{let active=true;fetch("./data/pen/comparison.json").then(r=>r.json() as Promise<Comparison>).then(c=>{if(active)setComparison(c)}).catch(()=>{});return()=>{active=false}},[]);
  const isMotorVariant=["ideal","motor","motor-hot"].includes(variant);
  const root=`./data/pen/${variant}${isMotorVariant&&trialView==="first"?"/first":""}`;
  const selector=<div className="hand-trial-selector"><label htmlFor="pen-variant">Physical comparison</label><select id="pen-variant" value={variant} onChange={e=>{setVariant(e.target.value);setMode(["motor","motor-hot"].includes(e.target.value)?"compare":"both")}}><option value="ideal">Simplified model · fixed torque limit</option><option value="motor">Motor-aware model · cold</option><option value="motor-hot">Motor-aware model · 100°C start</option><option value="baseline">Native Sharpa · supplied policy</option><option value="weak">Torque ceiling · 25% of baseline</option><option value="heavy">Hand mass and inertia · +50%</option></select>{isMotorVariant&&<><label htmlFor="pen-trial">Paired recording</label><select id="pen-trial" value={trialView} onChange={e=>setTrialView(e.target.value)}><option value="paired">Trial 1 · first simplified-model success</option><option value="first">Trial 0 · preselected first attempt</option></select></>}</div>;
  const [recording,setRecording]=useState<Recording|null>(null),[scene,setScene]=useState<SceneData|null>(null),[evaluation,setEvaluation]=useState<Evaluation|null>(null);
  const [error,setError]=useState(""),[time,setTime]=useState(0),[playing,setPlaying]=useState(false),[mode,setMode]=useState("compare");
  const clock=useRef({time:0,playing:false,speed:1});
  clock.current.playing=playing;
  useEffect(()=>{let active=true;setRecording(null);setError("");setPlaying(false);setTime(0);clock.current.time=0;Promise.all([loadScene("./data/pen/baseline/scene.json"),loadRecording(root),fetch(`${root}/evaluation.json`).then(r=>{if(!r.ok)throw Error("Evaluation unavailable");return r.json() as Promise<Evaluation>})]).then(([s,r,e])=>{if(active){setScene(s);setRecording(r);setEvaluation(e)}}).catch(e=>active&&setError(e.message));return()=>{active=false}},[root]);
  useEffect(()=>{let frame=0,last=performance.now();const tick=(now:number)=>{if(clock.current.playing&&recording){clock.current.time=Math.min(recording.result.duration,clock.current.time+Math.min((now-last)/1000,.1)*clock.current.speed);setTime(clock.current.time);if(clock.current.time>=recording.result.duration)setPlaying(false)}last=now;frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame)},[recording]);
  const seek=(t:number)=>{clock.current.time=t;setTime(t)};
  if(error)return <>{selector}<p role="alert">The pen recording could not be loaded: {error}</p></>;
  if(!recording||!scene||!evaluation)return <>{selector}<p role="status">Loading the Sharpa pen evaluation…</p></>;
  const sample=recording.samples[Math.min(recording.samples.length-1,Math.floor(time*recording.result.fps))] as any;
  const isModel=!!recording.result.motor_model;
  const jointData=sample.motor_joints;
  return <>{selector}<section className="motion-workbench"><div className="motion-stage">
    <div className="motion-heading"><span>Sharpa Wave · Pen spinning</span><span>PHYSX / {recording.result.physics_hz} Hz · REPLAY / 60 FPS</span></div>
    <div className="motion-phase"><h2>{sample.phase}</h2><p>{isModel?"Same policy and controller. Different predictions of delivered torque.":"Five fingers, one learned policy. The pen moves through physical contact."}</p></div>
    <div className={`motion-pair ${mode==="both"||mode==="compare"?"dual":""}`}>
      {mode==="compare"&&ideal&&<Replay sceneData={scene} recording={ideal} playback={clock} cameraView="overview" showPath={false} label={`Simplified · trial ${ideal.result.trial} · ${ideal.result.task_success?"motion pass":"motion fail"}`}/>}
      {mode!=="3d"&&mode!=="compare"&&<SyncedVideo src={`${root}/video.mp4`} clock={clock} label="Isaac measured-state render"/>}
      {mode!=="video"&&<Replay sceneData={scene} recording={recording} playback={clock} cameraView="overview" showPath={false} label={labels[variant]+` · trial ${recording.result.trial} · ${recording.result.task_success?"motion pass":"motion fail"}`}/>}
    </div>
    <div className="motion-toolbar"><Button aria-label={playing?"Pause":"Play"} onClick={()=>{if(time>=recording.result.duration)seek(0);setPlaying(!playing)}}>{playing?<Pause size={16}/>:<Play size={16}/>}</Button><Button aria-label="Restart" variant="ghost" onClick={()=>seek(0)}><RotateCcw size={16}/></Button><select aria-label="Playback speed" defaultValue="1" onChange={e=>{clock.current.speed=Number(e.target.value)}}><option value="0.25">0.25×</option><option value="0.5">0.5×</option><option value="1">1×</option></select><span>{time.toFixed(1)} / {recording.result.duration.toFixed(1)} s</span></div>
    <div className="transport"><Slider aria-label="Replay time" min={0} max={recording.result.duration} step={1/60} value={[time]} onValueChange={v=>seek(typeof v==="number"?v:v[0])}/></div>
  </div><aside className="motion-inspector"><p className="eyebrow">Recorded trial {recording.result.trial}</p><h2>{recording.result.task_success?"Three turns. Then hold.":"Recorded attempt."}</h2>
    <div className="motion-modes">{(isMotorVariant?["compare","both","video","3d"]:["both","video","3d"]).map(v=><Button key={v} variant={mode===v?"default":"ghost"} onClick={()=>setMode(v)}>{v==="compare"?"Compare models":v==="both"?"Video + 3D":v==="3d"?"3D replay":"Video"}</Button>)}</div>
    <dl className="motion-values"><dt>Net rotations</dt><dd>{sample.turns.toFixed(2)}</dd><dt>Pen angular speed</dt><dd>{sample.angular_speed_deg_s.toFixed(0)} °/s</dd><dt>{isModel?"Applied joint torque · peak":"Estimated drive torque now"}</dt><dd>{(isModel?sample.delivered_torque:sample.torque).toFixed(3)} Nm</dd>{fingers.map((f,i)=><span key={f} style={{display:"contents"}}><dt>{f} contact</dt><dd>{sample.finger_forces[i].toFixed(3)} N</dd></span>)}</dl>
    {isModel&&<><label htmlFor="motor-joint">Inspect joint</label><select id="motor-joint" value={joint} onChange={e=>setJoint(Number(e.target.value))}>{recording.result.motor_model.joint_names.map((name:string,i:number)=><option key={name} value={i}>{name.replace("right_","")}</option>)}</select>{jointData&&<dl className="motion-values"><dt>Requested torque</dt><dd>{jointData.requested[joint].toFixed(3)} Nm</dd><dt>Delivered torque</dt><dd>{jointData.applied[joint].toFixed(3)} Nm</dd><dt>Motor speed</dt><dd>{Math.abs(jointData.motor_rpm[joint]).toFixed(0)} RPM</dd>{jointData.current&&<><dt>Model current · peak dq</dt><dd>{jointData.current[joint].toFixed(2)} A</dd><dt>Model winding temperature</dt><dd>{jointData.temperature[joint].toFixed(1)} °C</dd></>}</dl>}</>}
    {isModel&&variant!=="ideal"&&<Button variant="outline" disabled={!recording.samples.some((r:any)=>r.torque_shortfall>1e-4)} onClick={()=>{let peak=0,selectedJoint=0,selectedTime=0;recording.samples.forEach((r:any)=>r.motor_joints.requested.forEach((request:number,j:number)=>{const gap=Math.abs(request-r.motor_joints.applied[j]);if(gap>peak){peak=gap;selectedJoint=j;selectedTime=r.t}}));setPlaying(false);setJoint(selectedJoint);seek(selectedTime)}}>Inspect largest torque shortfall</Button>}
    <p>{evaluation.motion_successes}/{evaluation.trials.length} trials complete three timed rotations and a supported one-second hold, within the motion limits. {evaluation.native_contact_successes}/{evaluation.trials.length} also pass the additional native contact and finger checks.</p>
    <p>The grasp is prepared before the recording. {isModel?recording.result.display_selection:"Trial 0 was selected before evaluation."} Every trial is reported below.</p>
  </aside></section>
  <section className="motion-analysis"><div><h2>Rotations through time</h2><ResponsiveContainer width="100%" height={240}><LineChart data={recording.samples.map((r:any,i:number)=>({...r,simplified:isMotorVariant?ideal?.samples[i]?.turns:undefined}))}><XAxis dataKey="t" type="number" domain={[0,recording.result.duration]}/><YAxis/><Tooltip/><Line name="Net rotations" dataKey="turns" stroke="#177960" dot={false} isAnimationActive={false}/><Line name="Simplified model" dataKey="simplified" stroke="#b58b45" dot={false} isAnimationActive={false}/><ReferenceLine y={3} stroke="#a48043" strokeDasharray="4 4"/><ReferenceLine x={time} stroke="#314f42"/></LineChart></ResponsiveContainer></div><div><h2>What the model changes</h2><p>This is a reproduction of the supplied <a href="https://github.com/jianglongye/dexterous-astra">Dexterous Astra</a> checkpoint with official Sharpa geometry. Atlas records and displays the Isaac body states; it did not train this checkpoint.</p><p>The simplified and motor-aware runs share the same explicit PD controller, gains and nominal stall torque. The simplified drive assumes that torque remains available at any speed. The motor-aware drive includes back EMF, voltage/current constraints, electrical lag, copper heating and thermal derating. The hot-start run begins at 100°C; it does not claim the hand heated to that temperature in twelve seconds. Motor parameters are assumed, not calibrated Sharpa measurements. The supplied policy was trained with native implicit actuation; this is a frozen-policy transfer test, not retraining. Contact checks use PhysX separations, so they differ from the reference’s independent collision audit.</p></div></section>
  {isModel&&<section className="motion-analysis"><div><h2>Requested vs delivered · selected joint</h2><ResponsiveContainer width="100%" height={260}><LineChart data={recording.samples.map((r:any)=>({t:r.t,requested:r.motor_joints?.requested[joint],delivered:r.motor_joints?.applied[joint]}))}><XAxis dataKey="t" type="number" domain={[0,recording.result.duration]}/><YAxis unit=" Nm" width={65}/><Tooltip/><Line name="Requested" dataKey="requested" stroke="#b58b45" dot={false} isAnimationActive={false}/><Line name="Delivered" dataKey="delivered" stroke="#177960" dot={false} isAnimationActive={false}/><ReferenceLine x={time} stroke="#314f42"/></LineChart></ResponsiveContainer></div><div><h2>Assumed motor design</h2><p>12 V bus · 2 A peak / 1 A continuous · 2 Ω phase resistance · 0.012 Nm/A torque constant · phase-peak Kv {recording.result.motor_model.phase_peak_Kv_rpm_per_V.toFixed(0)} RPM/V.</p><p>These are quasi-static current references with a first-order current loop, not a switching-inverter simulation. The twelve-second cold trials peaked at 30.1°C; the hot trials began at 100°C and cooled.</p><p>Joint gearing matches each native stall limit. Selected joint: {recording.result.motor_model.gear_ratio[joint].toFixed(1)}:1. Thermal resistance 10 K/W; thermal capacity 8 J/K. Mass, inertia and the policy remain fixed.</p><p>The native Sharpa reproduction is a separate reference because its controller is implicit. Compare the two explicit models to isolate torque-delivery assumptions.</p><a href={`${root}/result.json`}>Full parameters and provenance</a></div></section>}
  <section className="precision-results"><h2>Same policy. Different physical limits.</h2><p>The matched explicit runs completed 26/32 trials with fixed torque limits, 27/32 with the cold motor model, and 25/32 with a 100°C start. Cold torque delivery differed by less than 0.000001 Nm: its constraints did not bind here, so the one-trial difference is not evidence of an advantage. The hot model clipped up to 0.93 Nm. This batch does not establish a reliable success-rate separation.</p>{comparison&&<div style={{overflowX:"auto"}}><table><thead><tr><th>Configuration / controller</th><th>Motion successes</th><th>Additional contact checks</th><th>Trial 0 · third turn</th></tr></thead><tbody>{comparison.rows.map(r=><tr key={r.id}><td><Button variant="ghost" onClick={()=>{setVariant(r.id);setMode(["motor","motor-hot"].includes(r.id)?"compare":"both")}}>{labels[r.id]}</Button><small>{["ideal","motor","motor-hot"].includes(r.id)?" · explicit PD":" · native implicit"}</small></td><td>{r.motion_successes}/{r.trials}</td><td>{r.native_contact_successes}/{r.trials}</td><td>{r.selected_trial_third_turn_s===null?"Not reached":`${r.selected_trial_third_turn_s.toFixed(2)} s`}</td></tr>)}</tbody></table></div>}<p>Matched comparisons use the same prepared starting poses, pen mass and friction for each seed. These 32 development trials show sensitivity, not a reliable ranking of motor designs. Extra hand mass also increases inertia and does not necessarily reduce success on this task.</p><a href="./data/pen/comparison.json">Matched comparison data</a><h2>Every evaluation trial · {labels[variant]}</h2><div style={{overflowX:"auto"}}><table><thead><tr><th>Seed</th><th>Max net turns</th><th>Hold</th><th>Drop</th><th>Motion</th><th>Native contact gate</th></tr></thead><tbody>{evaluation.trials.map(r=><tr key={r.seed}><td>{r.seed}</td><td>{r.net_turns.toFixed(2)}</td><td>{r.hold_ok?"Yes":"No"}</td><td>{r.drop?"Yes":"No"}</td><td>{r.motion_passed?"Pass":"Fail"}</td><td>{r.native_contact_gate_passed?"Pass":"Fail"}</td></tr>)}</tbody></table></div><p>{evaluation.method}</p><a href={`${root}/evaluation.json`}>All numerical checks</a> · <a href={`${root}/result.json`}>Recording provenance</a> · <a href={`${root}/telemetry.json`}>Recorded telemetry</a> · <a href="./data/pen/SHARPA-LICENSE.txt">Sharpa asset license</a></section></>;
}
